### PR TITLE
Fix create backup

### PR DESCRIPTION
**Pull request by promatik**
- Added loading icon while creating backups
- Added notifications for all the events
- Removed jQuery dependency

This is an alternative to #103. But without Livewire, and jQuery 🙌

### CODE REVIEW

**Comment by promatik** [comment]
https://user-images.githubusercontent.com/1838187/160192975-ef999011-46be-44ee-a8b0-520626b689b7.mp4

**Review by tabacitu — APPROVED** [review]

**Comment by tabacitu** [comment]
I love it! Tested, seems to be working fine. But I don't want to give the thumbs-up for this, YOU should. We said this new release is your responsibility, so please @pxpm take a look and let us know if I should merge and tag the release, if it's all done now.

Happy to see this papercut finally get fixed! 🎉

**Comment by tabacitu** [comment]
(please mind the README too... is there an upgrade guide from one version to the other? the config will probably need some upgrade instructions)

**Comment by promatik** [comment]
@pxpm since I added some minor commits, I'll let you give the final approval 🙌
From my side, everything tested and working 👌

**Comment by tabacitu** [comment]
@pxpm I messed up... 😔 I merged the wrong stuff to the wrong branches. The releases seem to be fine (I hope) but the branches no. I know for sure that:
- I incorrectly merged https://github.com/Laravel-Backpack/BackupManager/pull/107 into `master` but that was meant for `v3`
- I incorrectly merged https://github.com/Laravel-Backpack/BackupManager/pull/104 into `v3` when it was meant for `v4`

I didn't check if they were pointing to the right branch 😔

I've just spent the time now to clean it up (hence the revert in https://github.com/Laravel-Backpack/BackupManager/pull/110 ). But please double-check me. Now we should be having:
- `v3` - no breaking changes;
- `v4` - yes breaking changes (no config file), everything we need for the new release should be here, all new PRs for v4 should point to this one;
- `master`  - same as v4 for now; or something like that; but let's ignore it until we publish v4;

Can you please double-check that this is what we've got? From what I can tell, what I need to do further is:
- [ ] tag 3.0.8 from the `v3` branch, so it has the unknown_disk too;
- [ ] merge this last PR into `v4` and tag 4.0.0 from there;
- [ ] merge `v4` into `master` and delete `v4`;

You think I'm correct? Can you please fix the conflicts here so it's ready for v4, and check we have everything we need in this branch to launch?

Thanks! And sorry for the mistakes - my bad!

**Comment by pxpm** [comment]
@tabacitu I tested in a 4.1 project, and in a new v5, the master branch and v4 (after merging the conflicts), I think everything is ok, so no big deal about the branch confusion, I am sure that __the guilt does not die single__ (portuguese saying that means there is not only one to blame), we both didn't notice/change the branches at an appropriate time, sorry on my part here! 

🙏

**Pull request merged**
