### PR TITLE
BackupManage v4 Release

### PR DESCRIPTION
**Pull request by tabacitu**
@pxpm let me know if/when this is ready to merge & tag. Also please give me some pointers into what we should write inside the release markdown itself... because this is what we have now:

CleanShot 2022-04-05 at 13 26 14

See... if we properly named our PRs... this would have been better already 😅

---

What does this new version offer, that v3 didn't? What are the considerable changes?

### CODE REVIEW

**Comment by tabacitu** [comment]
Tagged this as a MUST just because I want to forget about BackupManager for a while 😅

**Comment by pxpm** [comment]
@tabacitu I would say that this adds:

- improve backup operations feedback
- remove jquery dependency
- support only lastest spatie-backup version (v8)

**Comment by tabacitu** [comment]
Gonna also change the readme image to a gif:

CleanShot 2022-04-06 at 11 32 06

**Comment by tabacitu** [comment]
Checked, works like a charm! 🎉🎉🎉 Just edited the README a little but to clean it up, but other than that... VERY happy with this release. Good job guys!!! Merging & tagging 💪

**Pull request merged**
