### PR TITLE
Configurable ini settings for backups

### PR DESCRIPTION
**Pull request by pxpm**
refs: #82 

By default we would change ini settings when creating the backup.

Those settings were hardcoded.

Now developer has the chance to change default backpack ini settings values so as to add other settings.

### CODE REVIEW

**Comment by tabacitu** [comment]
Excellent addition. Looks backwards-compatible too, am I wrong? The config option should be picked up from the vendor folder if missing in the userland config file, I think.

**Comment by promatik** [comment]
@pxpm, @tabacitu I'm afraid this isn't backwards-compatible ...

Take a look at this;
https://github.com/Laravel-Backpack/BackupManager/blob/master/src/BackupManagerServiceProvider.php#L32

```php
$this->mergeConfigFrom(
  __DIR__.'/config/backup.php',
  'backpack.backupmanager'
);
```

BackupManager publishes the config to `config/backup.php` but then it merges default configs on `backpack.backupmanager`.

Is this some legacy way?

There is an open issue related to this, to start using spatie config; https://github.com/Laravel-Backpack/BackupManager/issues/68.
Maybe both problems should be solved on BackupManager v4.

--- 
By the way, this looks really nice, it's a great idea for BackupManager, I'm wondering if it would be a good addition to backpack base/crud?
It's a nice helper but maybe heavy? maybe crud shouldn't go that way?
Just asking 😅

**Comment by tabacitu** [comment]
Nice catch @promatik !

> BackupManager publishes the config to config/backup.php but then it merges default configs on backpack.backupmanager. Is this some legacy way?

So what's happening here is that BackupManager doesn't _actually_ have a config file. What this package includes is the config file for the `spatie/backup` package. We've added our own config value at the top of it (`backpack_flags`) and upon installation we publish it. What makes it confusing is that we do have the ServiceProvider wiring for having a package config file. It's just that AFAIK it's not used. Or the config file is loaded by both BackupManager and SpatieBackup or something.

We should probably do what https://github.com/Laravel-Backpack/BackupManager/issues/68 said - that guy seems to know what he's talking about 😉 Plus, this is a very weird way to do configs in Laravel, can't remember how/why we decided to do it like this but it feels messy now.

Let's call this a breaking change, I agree.

> By the way, this looks really nice, it's a great idea for BackupManager, I'm wondering if it would be a good addition to backpack base/crud?

Mneah... Changing ini variables feels like cheating to me... Whenever I use them I realise that I could probably optimise the process. Perhaps using it in a niche package like this won't do that much harm, but I really wouldn't do it inside the Backpack core, I think it'd encourage a bad practice.

**Comment by pxpm** [comment]
done in #102 👍 closing

**Pull request closed without merging**
