### PR TITLE
update backup.php

### PR DESCRIPTION
**Pull request by shuxx**
Fix backup name to "Sauvegardes" makes more meaning on display

### CODE REVIEW

**Comment by pxpm** [comment]
Hello @shuxx 

Thanks for one more contribution. 

Let me just clarify cause I am not an french speaker. I know `Bonjour` :)

```php
backup => Sauvegarde
backups => Sauvegardes
```

Is this correct ? If so, there is no sense in the key beeing `backup` and the meaning is `backups`. You understand what I mean here ? 

Best,
Pedro

**Comment by shuxx** [comment]
Ur right but in this particular case," backups" shoulds be display in the view for title instead of "backup" becauses it showings all the backups not only one right ? so Sauvegarde should take an S...

**Comment by promatik** [comment]
@pxpm I think the main issue here, is backpack was wrong since the beginning 😅
This specific translation is used as the title of the entity, and these titles are always in the plural;
- Settings
- Users
- Pages
- Menu Items

image

The exception is **Backup**, that should be **Backups** 🤷‍♂️

That being said, I think we should either;
- change all the translations to plural `'backup' => 'Backups'`.
- introduce another key `'backups' => 'Backups'`.
- don't change anything because developers may change it on their side(?)

It's kinda a lot of work for such a simple thing 😬
I suggest to move this to v4.2, and this about it later.
@pxpm bring this to v4.1 if you think we should address this now.

**Comment by tabacitu** [comment]
I'd go with both `backup` and `backups` in all language files. Because we could consider that non-breaking...

**Comment by pxpm** [comment]
@tabacitu I agree with you, having both strings would make it a non-breaking change, but how about https://github.com/Laravel-Backpack/BackupManager/blob/847c935f78429d34ac068597e0e38ff6ae7cf7e8/src/resources/views/backup.blade.php#L13

We have the strings but would show `Backup` 🙃 I think changing here for `backup.backups` would be a BC ? I am not sure. 

ping @tabacitu

**Comment by tabacitu** [comment]
We could use `backups` as the default there, and fall back to `backup` if that doesn't exist... That way it's a non-breaking change... right?

**Comment by promatik** [comment]
I think this one is also ready to merge, as a breaking change.

**Pull request merged**
